import {
    AddToPlaylist,
    CreatePlaylist,
    GetFilters,
    GetLastPlayed,
    GetMusicDir,
    GetPlaylists,
    GetStreamBaseURL,
    GetSystemVolume,
    ListMusicFiles,
    ReadMusicFile,
    SetFilters,
    SetLastPlayed,
    SetSystemVolume,
} from '../../wailsjs/go/main/App';

export const api = {
    addToPlaylist: AddToPlaylist,
    createPlaylist: CreatePlaylist,
    getFilters: GetFilters,
    getLastPlayed: GetLastPlayed,
    getMusicDir: GetMusicDir,
    getPlaylists: GetPlaylists,
    getStreamBaseURL: GetStreamBaseURL,
    getSystemVolume: GetSystemVolume,
    listMusicFiles: ListMusicFiles,
    readMusicFile: ReadMusicFile,
    setFilters: SetFilters,
    setLastPlayed: SetLastPlayed,
    setSystemVolume: SetSystemVolume,
};
