import {
  AddToPlaylist,
  CreatePlaylist,
  GetFilters,
  GetLastPlayed,
  GetMusicDir,
  GetMusicDirs,
  GetPlaylists,
    GetStreamBaseURL,
    GetSystemVolume,
    GetTheme,
    ListMusicFiles,
    PickMusicDir,
    ReadMusicFile,
    SetFilters,
    SetLastPlayed,
    SetMusicDir,
    SetMusicDirs,
    SetSystemVolume,
    SetTheme,
} from '../../wailsjs/go/main/App';

export const api = {
  addToPlaylist: AddToPlaylist,
  createPlaylist: CreatePlaylist,
  getFilters: GetFilters,
  getLastPlayed: GetLastPlayed,
  getMusicDir: GetMusicDir,
  getMusicDirs: GetMusicDirs,
  getPlaylists: GetPlaylists,
    getStreamBaseURL: GetStreamBaseURL,
    getSystemVolume: GetSystemVolume,
    getTheme: GetTheme,
    listMusicFiles: ListMusicFiles,
    pickMusicDir: PickMusicDir,
    readMusicFile: ReadMusicFile,
  setFilters: SetFilters,
  setLastPlayed: SetLastPlayed,
    setMusicDir: SetMusicDir,
    setMusicDirs: SetMusicDirs,
    setSystemVolume: SetSystemVolume,
    setTheme: SetTheme,
};
