// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToPlaylist(arg1, arg2) {
  return window['go']['app']['App']['AddToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['app']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['app']['App']['DeletePlaylist'](arg1);
}

export function GetActivePlaylist() {
  return window['go']['app']['App']['GetActivePlaylist']();
}

export function GetFilters() {
  return window['go']['app']['App']['GetFilters']();
}

export function GetLastPlayed() {
  return window['go']['app']['App']['GetLastPlayed']();
}

export function GetLastPlayedRecord() {
  return window['go']['app']['App']['GetLastPlayedRecord']();
}

export function GetMusicDir() {
  return window['go']['app']['App']['GetMusicDir']();
}

export function GetMusicDirs() {
  return window['go']['app']['App']['GetMusicDirs']();
}

export function GetPlaylists() {
  return window['go']['app']['App']['GetPlaylists']();
}

export function GetStreamBaseURL() {
  return window['go']['app']['App']['GetStreamBaseURL']();
}

export function GetSystemVolume() {
  return window['go']['app']['App']['GetSystemVolume']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function ListMusicFiles() {
  return window['go']['app']['App']['ListMusicFiles']();
}

export function PickMusicDir(arg1) {
  return window['go']['app']['App']['PickMusicDir'](arg1);
}

export function ReadMusicFile(arg1) {
  return window['go']['app']['App']['ReadMusicFile'](arg1);
}

export function RemoveFromPlaylist(arg1, arg2) {
  return window['go']['app']['App']['RemoveFromPlaylist'](arg1, arg2);
}

export function SetActivePlaylist(arg1) {
  return window['go']['app']['App']['SetActivePlaylist'](arg1);
}

export function SetFilters(arg1, arg2) {
  return window['go']['app']['App']['SetFilters'](arg1, arg2);
}

export function SetLastPlayed(arg1) {
  return window['go']['app']['App']['SetLastPlayed'](arg1);
}

export function SetMusicDir(arg1) {
  return window['go']['app']['App']['SetMusicDir'](arg1);
}

export function SetMusicDirs(arg1) {
  return window['go']['app']['App']['SetMusicDirs'](arg1);
}

export function SetSystemVolume(arg1) {
  return window['go']['app']['App']['SetSystemVolume'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function UpdateTrayPlayback(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateTrayPlayback'](arg1, arg2, arg3);
}
