// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';
import {media} from '../models';

export function AddToPlaylist(arg1:string,arg2:string):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function GetActivePlaylist():Promise<string>;

export function GetFilters():Promise<string>;

export function GetLastPlayed():Promise<string>;

export function GetLastPlayedRecord():Promise<state.LastPlayedRecord>;

export function GetMusicDir():Promise<string>;

export function GetMusicDirs():Promise<Array<string>>;

export function GetPlaylists():Promise<Array<state.Playlist>>;

export function GetStreamBaseURL():Promise<string>;

export function GetSystemVolume():Promise<number>;

export function GetTheme():Promise<string>;

export function ListMusicFiles():Promise<Array<media.MusicFile>>;

export function PickMusicDir(arg1:string):Promise<string>;

export function ReadMusicFile(arg1:string):Promise<Array<number>>;

export function RemoveFromPlaylist(arg1:string,arg2:string):Promise<void>;

export function SetActivePlaylist(arg1:string):Promise<void>;

export function SetFilters(arg1:string,arg2:string):Promise<void>;

export function SetLastPlayed(arg1:string):Promise<void>;

export function SetMusicDir(arg1:string):Promise<string>;

export function SetMusicDirs(arg1:Array<string>):Promise<Array<string>>;

export function SetSystemVolume(arg1:number):Promise<number>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateTrayPlayback(arg1:string,arg2:boolean,arg3:string):Promise<void>;
