// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusicDir() {
  return window['go']['main']['App']['GetMusicDir']();
}

export function ListMusicFiles() {
  return window['go']['main']['App']['ListMusicFiles']();
}

export function ReadMusicFile(arg1) {
  return window['go']['main']['App']['ReadMusicFile'](arg1);
}
