// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToPlaylist(arg1:string,arg2:string):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<void>;

export function GetFilters():Promise<string>;

export function GetLastPlayed():Promise<string>;

export function GetMusicDir():Promise<string>;

export function GetMusicDirs():Promise<Array<string>>;

export function GetPlaylists():Promise<Array<main.Playlist>>;

export function GetStreamBaseURL():Promise<string>;

export function GetSystemVolume():Promise<number>;

export function GetTheme():Promise<string>;

export function GetTheme():Promise<string>;

export function ListMusicFiles():Promise<Array<main.MusicFile>>;

export function PickMusicDir(arg1:string):Promise<string>;

export function ReadMusicFile(arg1:string):Promise<Array<number>>;

export function SetFilters(arg1:string,arg2:string):Promise<void>;

export function SetLastPlayed(arg1:string):Promise<void>;

export function SetMusicDir(arg1:string):Promise<string>;

export function SetMusicDirs(arg1:Array<string>):Promise<Array<string>>;

export function SetSystemVolume(arg1:number):Promise<number>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
