// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMusicDir():Promise<string>;

export function ListMusicFiles():Promise<Array<main.MusicFile>>;

export function ReadMusicFile(arg1:string):Promise<Array<number>>;
