// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function GetFilters() {
  return window['go']['main']['App']['GetFilters']();
}

export function GetLastPlayed() {
  return window['go']['main']['App']['GetLastPlayed']();
}

export function GetMusicDir() {
  return window['go']['main']['App']['GetMusicDir']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function GetStreamBaseURL() {
  return window['go']['main']['App']['GetStreamBaseURL']();
}

export function ListMusicFiles() {
  return window['go']['main']['App']['ListMusicFiles']();
}

export function ReadMusicFile(arg1) {
  return window['go']['main']['App']['ReadMusicFile'](arg1);
}

export function SetFilters(arg1, arg2) {
  return window['go']['main']['App']['SetFilters'](arg1, arg2);
}

export function SetLastPlayed(arg1) {
  return window['go']['main']['App']['SetLastPlayed'](arg1);
}
